apiVersion: v1
kind: Service
metadata:
  name: backend-feed-red
spec:
  selector:
    app: backend-feed
    color: red
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: backend-feed