apiVersion: v1
kind: Service
metadata:
  name: backend-feed-green
spec:
  selector:
    app: backend-feed
    color: green
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: backend-feed