version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: mehmetsatilmis/reverseproxy
  backend_user:
    build:
      context: ../../udacity-c2-restapi-user
    image: mehmetsatilmis/udagram-user
  backend_feed:
    build:
      context: ../../udacity-c2-restapi-feed  
    image: mehmetsatilmis/udagram-feed
  frontend:
    build:
      context: ../../udacity-c2-frontend  
    image: mehmetsatilmis/udagram-frontend
